### ISSUE TITLE
Results writer fails with IndexError: list index out of range 

### ISSUE THREAD

**Issue by dave00galloway** [dave00galloway/multi-mechanize#1]
Results generation fails with -
```

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/local/lib/python2.7/site-packages/multimechanize/utilities/run.py", line 228, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/multimechanize/utilities/run.py", line 59, in main
    rerun_results(cmd_opts.results_dir)
  File "/usr/local/lib/python2.7/site-packages/multimechanize/utilities/run.py", line 167, in rerun_results
    results.output_results(output_dir, 'results.csv', run_time, rampup, results_ts_interval, user_group_configs, xml_report)
  File "/usr/local/lib/python2.7/site-packages/multimechanize/results.py", line 152, in output_results
    splat_series = split_series(custom_timer_points, interval_secs)
  File "/usr/local/lib/python2.7/site-packages/multimechanize/results.py", line 317, in split_series
    offset = points[0][0]
IndexError: list index out of range
```

**Comment by dave00galloway** [comment]
fixed merged to master in https://github.com/dave00galloway/multi-mechanize. will raise PR to https://github.com/cgoldberg/multi-mechanize
